/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/building.gltf");
  console.log({ materials });
  materials.apartment_material.transparent = true;
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        material={materials.apartment_material}
        geometry={nodes.apartment_small_mesh.geometry}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[1, 1, 1]}
      />
    </group>
  );
}

useGLTF.preload("/building.gltf");
